modem.generic.cell-info.length   : 5
modem.generic.cell-info.value[1] : cell type: lte, serving: no, physical ci: F3, earfcn: 1602, rsrp: -95.700000, rsrq: -18.100000
modem.generic.cell-info.value[2] : cell type: lte, serving: no, physical ci: A0, earfcn: 1602, rsrp: -92.700000, rsrq: -13.600000
modem.generic.cell-info.value[3] : cell type: lte, serving: no, physical ci: 102, earfcn: 2850, rsrp: -92.200000, rsrq: -9.000000
modem.generic.cell-info.value[4] : cell type: lte, serving: no, physical ci: A0, earfcn: 1458, rsrp: -87.600000, rsrq: -11.500000
modem.generic.cell-info.value[5] : cell type: lte, serving: yes, operator id: 25002, tac: 2364, ci: 1A8D1AB, physical ci: 102, earfcn: 3048, rsrp: -86.400000, rsrq: -10.200000
