sms.dbus-path                      : /org/freedesktop/ModemManager1/SMS/0
sms.content.number                 : +79162070281
sms.content.text                   : Test 19:43
sms.content.data                   : --
sms.properties.pdu-type            : deliver
sms.properties.state               : received
sms.properties.validity            : --
sms.properties.storage             : me
sms.properties.smsc                : +79262000147
sms.properties.class               : --
sms.properties.teleservice-id      : --
sms.properties.service-category    : --
sms.properties.delivery-report     : --
sms.properties.message-reference   : --
sms.properties.timestamp           : 2026-06-21T19:43:17+03
sms.properties.delivery-state      : --
sms.properties.discharge-timestamp : --
