sms.dbus-path                      : /org/freedesktop/ModemManager1/SMS/1
sms.content.number                 : +79162070281
sms.content.text                   : test
sms.content.data                   : --
sms.properties.pdu-type            : submit
sms.properties.state               : --
sms.properties.validity            : --
sms.properties.storage             : --
sms.properties.smsc                : --
sms.properties.class               : --
sms.properties.teleservice-id      : --
sms.properties.service-category    : --
sms.properties.delivery-report     : not requested
sms.properties.message-reference   : --
sms.properties.timestamp           : --
sms.properties.delivery-state      : --
sms.properties.discharge-timestamp : --
